version: 0.2

env:
  variables:
    ENV: "test"
    DOCKER_VERSION: 18

phases:
  install:
    runtime-versions:
      docker: ${DOCKER_VERSION}
    commands:
      - echo install dependencies ...
    finally:
      - echo finish to install dependencies ...
  pre_build:
    commands:
      - echo build docker image ...
      - ./build-docker-image
    finally:
      - echo finish to build docker image ...
  build:
    commands:
      - echo run unit test ...
      - echo run code style check ...
      - sleep 5
      - echo run dependencies check ...
      - echo the env is ${ENV}
      - sleep 5
      - echo the docker version is ${DOCKER_VERSION}
      - ./build-docker-image
      - echo login ecr
      - echo push image
    finally:
      - echo finish to build
  post_build:
    commands:
      - echo done, cleanup ...
