version: 0.2

env:
  variables:
    ENV: "test"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo install dependencies ...
    finally:
      - echo finish to install dependencies ...
  pre_build:
    commands:
      - echo build docker image ...
      - ./build-docker-image
    finally:
      - echo finish to build docker image ...
  build:
    commands:
      - echo run unit test ...
      - echo run code style check ...
      - echo run dependencies check ...
      - echo run integration test ...
      - echo run e2e test ...
      - echo the env is ${ENV}
      - ./build-docker-image
      - echo login ecr
      - echo push image
    finally:
      - echo finish to build
  post_build:
    commands:
      - echo done, cleanup ...
